# Generated by Django 5.0.6 on 2024-05-22 03:29

from django.db import migrations
from django.contrib.auth.hashers import make_password
import os

def create_initial_users(apps, schema_editor):
    """
    Crea los usuarios iniciales (admin y estudiante) si no existen.
    Dentro de las migraciones, los métodos del modelo como set_password no están disponibles.
    En su lugar, hasheamos la contraseña manualmente con make_password.
    """
    Usuario = apps.get_model('usuarios', 'Usuario')
    
    admin_email = 'admin@mtiglobaltech.com'
    student_email = 'estudiante@gmail.com'
    admin_password = os.environ.get('ADMIN_PASSWORD', 'AdminPass123!')
    student_password = os.environ.get('STUDENT_PASSWORD', 'StudentPass123!')

    # Crear superusuario si no existe
    if not Usuario.objects.filter(email=admin_email).exists():
        Usuario.objects.create(
            email=admin_email,
            nombre_completo='Administrador',
            password=make_password(admin_password), # Hashear contraseña
            rol='administrador',
            is_staff=True,
            is_superuser=True
        )

    # Crear usuario estudiante si no existe
    if not Usuario.objects.filter(email=student_email).exists():
        Usuario.objects.create(
            email=student_email,
            nombre_completo='Estudiante de Prueba',
            password=make_password(student_password), # Hashear contraseña
            rol='estudiante'
        )

def revert_users(apps, schema_editor):
    """
    Elimina los usuarios creados inicialmente.
    """
    Usuario = apps.get_model('usuarios', 'Usuario')
    Usuario.objects.filter(email__in=['admin@mtiglobaltech.com', 'estudiante@gmail.com']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_users, reverse_code=revert_users),
    ]
